### ISSUE TITLE
Cannot send email with headers or attachments and tuple-based Reply-To address 

### ISSUE THREAD

**Issue by michallepicki** [kalys/bamboo_ses#54]
👋🏻 Hello! Thanks for your library!

When reading the code, it seemed that it can handle `Reply-To` header values set to `{name, address}` tuples, just like some other destination headers, which is very convenient ([code](https://github.com/kalys/bamboo_ses/blob/9c4fa6042ba581852ba0047e2232708ef7a712b4/lib/bamboo/adapters/ses_adapter.ex#L160)). But when sending such email with also custom headers or attachments (so that the Raw message type will have to be used):
```elixir
   TestHelpers.new_email()
   |> Email.put_header("X-Custom-Header", "header-value")
   |> Email.put_header("Reply-To", {"Reply To", "reply-to@example.com"})
   |> SesAdapter.deliver(%{})
```

there is an error somewhere from the Raw message renderer (`BambooSes.Render.Raw`):

```
     ** (FunctionClauseError) no function clause matching in :smtp_util.parse_rfc5322_addresses/1

     The following arguments were given to :smtp_util.parse_rfc5322_addresses/1:

         # 1
         {"Reply To", "reply-to@example.com"}

     code: |> SesAdapter.deliver(%{})
     stacktrace:
       (gen_smtp 1.2.0) /home/michal/bamboo_ses/deps/gen_smtp/src/smtp_util.erl:255: :smtp_util.parse_rfc5322_addresses/1
       (gen_smtp 1.2.0) /home/michal/bamboo_ses/deps/gen_smtp/src/mimemail.erl:999: :mimemail.encode_header_value/2
       (gen_smtp 1.2.0) /home/michal/bamboo_ses/deps/gen_smtp/src/mimemail.erl:963: :mimemail.encode_headers/1
       (gen_smtp 1.2.0) /home/michal/bamboo_ses/deps/gen_smtp/src/mimemail.erl:964: :mimemail.encode_headers/1
       (gen_smtp 1.2.0) /home/michal/bamboo_ses/deps/gen_smtp/src/mimemail.erl:210: :mimemail.encode/2
       (bamboo_ses 0.4.4) lib/bamboo/adapters/message/content.ex:87: BambooSes.Message.Content.build_content/7
       (bamboo_ses 0.4.4) lib/bamboo/adapters/message.ex:136: BambooSes.Message.put_content/2
       (bamboo_ses 0.4.4) lib/bamboo/adapters/ses_adapter.ex:51: Bamboo.SesAdapter.deliver/2
```

(I think the `BambooSes.Render.Raw` module is missing from the stacktrace due to Erlang's tail-call optimizations)

It seems that `BambooSes.Render.Raw` was mostly copied [from `mailman`](https://github.com/mailman-elixir/mailman/blob/master/lib/mailman/render.ex) and uses `gen_smtp`'s `mimemail` to create the resulting `MIME` email envelope, which expects the `Reply-To` header to be a binary, which it parses (for some reason) before including in the message.

Is this a bug? Does this library intend to handle `Reply-To` headers in form of tuples, or not?

**Comment by michallepicki** [comment]
Looks like even though [`Bamboo.Email.put_header/3` spec](https://hexdocs.pm/bamboo/Bamboo.Email.html#put_header/3) says the value should be a String, even some of the official adapters do support `Reply-To` in form of tuples, e.g. [the SendGrid adapter does support it](https://github.com/beam-community/bamboo/blob/6166ef74c7a4f5740153c6e7b5473110cf3bfc00/lib/bamboo/adapters/send_grid_adapter.ex#L214)
